DROP TABLE IF EXISTS Asiakas CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE;
DROP TABLE IF EXISTS Kategoria CASCADE;
DROP TABLE IF EXISTS Tarjous CASCADE;
DROP TABLE IF EXISTS Tuotekategoria CASCADE;

DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Offer CASCADE;
DROP TABLE IF EXISTS Productcategory CASCADE;
